################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
HALCoGen-TMS570LC43x/source/HL_emac.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_emac.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_epc.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_epc.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_errata.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_errata.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_esm.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_esm.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_gio.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_gio.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_mdio.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_mdio.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_nmpu.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_nmpu.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_notification.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_notification.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_phy_dp83640.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_phy_dp83640.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_phy_tlk111.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_phy_tlk111.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_pinmux.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_pinmux.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_sci.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_sci.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_sys_core.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_sys_core.asm $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_sys_dma.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_sys_dma.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_sys_intvecs.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_sys_intvecs.asm $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_sys_main.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_sys_main.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_sys_mpu.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_sys_mpu.asm $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_sys_pcr.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_sys_pcr.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_sys_phantom.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_sys_phantom.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_sys_pmm.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_sys_pmm.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_sys_pmu.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_sys_pmu.asm $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_sys_selftest.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_sys_selftest.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_sys_startup.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_sys_startup.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_sys_vim.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_sys_vim.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HALCoGen-TMS570LC43x/source/HL_system.obj: C:/ti/Hercules/HALCoGen\ EMAC\ Driver\ with\ lwIP\ Demonstration/v00.03.00/TMS570LC43x_LP/HALCoGen-TMS570LC43x/source/HL_system.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.4.LTS/include" --include_path="C:/Users/a0324020/workspace_v8/TMS570LC4357_FreeRTOS_LWIP" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/example/hdk/inc" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/src/include/ipv4" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/check" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/include" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk/netif" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/ports/hdk" --include_path="C:/ti/Hercules/HALCoGen EMAC Driver with lwIP Demonstration/v00.03.00/lwip-1.4.1/apps/httpserver_raw" --define=_TMS570LC43x_ -g --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --endian=big --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LC43x/source/$(basename $(<F)).d_raw" --obj_directory="HALCoGen-TMS570LC43x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


